name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.0'

      - name: Build app
        run: flutter build web
        working-directory: ./berean_bible_app

      - name: Deploy to Another Repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git clone https://x-access-token:${{ secrets.NinjaToken }}@github.com/BereanBible/BereanBible.github.io.git
          cp -r ./berean_bible_app/build/web/* ./BereanBible.github.io/
          cd BereanBible.github.io
          git add .
          git commit -m "Update from GitHub Actions"
          git push
        env:
          PAT: ${{ secrets.NinjaToken }}